### ISSUE TITLE
Numpy Install Requirement

### ISSUE THREAD

**Issue by greenstick** [greenstick/bootstrapping-package-management-on-exacloud#1]
This is to serve as documentation of an error that I was notified of by email:

> I downloaded it as you described in the tutorial
`>> /home/users/emechebe/packages/miniconda2`

> However when I ran this:
`>> conda install gcc`

> I got this scary error message
```
Traceback (most recent call last):
  File "/home/users/emechebe/packages/miniconda2/bin/conda", line 4, in <module>
    import conda.cli
  File "/home/users/emechebe/packages/miniconda2/lib/python2.7/site-packages/conda/__init__.py", line 12, in <module>
    from .compat import text_type, iteritems
  File "/home/users/emechebe/packages/miniconda2/lib/python2.7/site-packages/conda/compat.py", line 11, in <module>
    from tempfile import mkdtemp
  File "/home/users/emechebe/packages/miniconda2/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/lib64/python2.6/site-packages/scipy/io/__init__.py", line 7, in <module>
    from numpy import deprecate_with_doc
ImportError: No module named numpy
```

**Comment by greenstick** [comment]
Updated command in README.md and made a note.

**Comment by greenstick** [comment]
Update: User mentioned issue may have been cause by incorrect configuration of their `PYTHON_PATH`. There's a good chance this issue is not relevant to most people installing Miniconda.
